---
abstract: 'Interface to the calendar used by Bahai faith.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Date::Calc: 5.7
  List::Util: 1.21
  Readonly: 0
  Test::More: 0
  Time::localtime: 1.02
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Calendar-Bahai
provides:
  Calendar::Bahai:
    file: lib/Calendar/Bahai.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
